group=me.berko
version=3.1
description=GelenceSignShop is a plugin for Spigot servers that allows players to buy and sell items using signs. It is designed to be easy to use and highly customizable, making it a great choice for server owners who want to add an economy system to their server.

org.gradle.configuration-cache=true
org.gradle.parallel=true
org.gradle.caching=true

